{
 "title": "llama.cpp",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "llama.cpp Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "# Hosted LLM\n\nThis dashboard is part of the AI initiative at Camptocamp IS (#is-ai) to host a LLM (Meta-Llama-3-8B-Instruct) on a souvereign cloud provider (Exoscale). The application is llama.cpp.\n\n"
   }
  },
  { "title": "Requests Current and Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Current Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:requests_processing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Processing",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 17, "x": 6, "y": 5 },
   "targets": [
    { "expr": "llamacpp:requests_processing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(llamacpp:requests_processing[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Deferred",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 17, "x": 6, "y": 9 },
   "targets": [
    { "expr": "llamacpp:requests_deferred", "legendFormat": "__auto" }
   ]
  },
  { "title": "Tokens Predicted and Prompts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Tokens Predicted Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp:tokens_predicted_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt Tokens Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:prompt_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Token Predicted Seconds Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp:tokens_predicted_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predicted Tokens Seconds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp:predicted_tokens_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt Seconds Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:prompt_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prompt Tokens Seconds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:prompt_tokens_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "KV Cache Tokens",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:kv_cache_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Cache Usage Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:kv_cache_usage_ratio", "legendFormat": "__auto" }
   ]
  }
 ]
}