{{- if  .Values.nvidiaUtilities.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-utilities
  namespace: {{ .Values.argoCD.namespace | default "argocd" }}
  labels:
    application: nvidia-utilities
spec:
  project: {{ .Values.argoCD.project | default "llm-apps" }}
  
  source:
    repoURL: https://github.com/camptocamp/self-hosted-llm-models-charts.git
    targetRevision: main
    path: charts/nvidia-utilities
    {{- with .Values.nvidiaUtilities.valuesObject }}
    helm:
      valuesObject:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  
  destination:
    name: in-cluster
    namespace: nvidia-utilities

  syncPolicy:
    {{- if .Values.nvidiaUtilities.autoSync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    {{- end }}
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m
{{- end -}}
