apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: tgi
  labels:
    app: text-generation-inference
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-inference
  namespace: tgi
  labels:
    app: text-generation-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-generation-inference
  template:
    metadata:
      labels:
        app: text-generation-inference
    spec:
      containers:
      - name: text-generation-inference
        image: ghcr.io/huggingface/text-generation-inference:latest
        command:
        - text-generation-launcher
        args:
        - --model-id
        - meta-llama/Meta-Llama-3-8B-Instruct
        env:
        - name: PORT
          value: "8080"
        - name: HUGGINGFACE_OFFLINE
          value: "1"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: model-storage
          mountPath: /data
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: 3
            memory: 10Gi
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - llm
      tolerations:
      - key: nodepool
        operator: Equal
        value: llm
        effect: NoSchedule
