apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  labels:
    app: text-generation-inference
spec:
  resources:
    requests:
      storage: 300Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn

