---
name: "Automatic terraform apply on push to main"

on:
  push:
    branches:
    - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      TF_ACTION_WORKING_DIR: ./terraform
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
      TF_VAR_exoscale_iam_key: ${{ secrets.EXOSCALE_API_KEY }}
      TF_VAR_exoscale_iam_secret: ${{ secrets.EXOSCALE_API_SECRET }}

    steps:

    - name: "Checkout the repository"
      uses: actions/checkout@v4

    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v3

    - name: "Run terraform init"
      id: init
      run: "terraform init -no-color"
    
    - name: "Run terraform validate"
      id: validate
      run: "terraform validate -no-color"

    - name: "Run terraform plan"
      id: plan
      run: "terraform plan -no-color -input=false -out tfplan"

    - name: "Run terraform apply"
      run: "terraform apply -no-color -auto-approve -input=false tfplan"
